### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by fengwang** [heyvaldemar/outline-keycloak-traefik-letsencrypt-docker-compose#1]
After having mapped keycloak.outline.heyvaldemar.net and outline.heyvaldemar.net to my server ip, I followed the actions in the article,  but still cannot login with keycloak. Input my user name and password, I was redirected to Authentication failed page with url https://outline.heyvaldemar.net/?notice=auth-error.

The outline container log gives error message like
```
{"error":"getaddrinfo ENOTFOUND keycloak.outline.heyvaldemar.net","level":"error","message":"Error during authentication","stack":"Error: getaddrinfo ENOTFOUND keycloak.outline.heyvaldemar.net\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)"}
```

Any suggestions to debug/fix?

**Comment by heyvaldemar** [comment]
It would help if you used your domain and make sure that DNS is set correctly.

We can discuss it more on my [Discord server](https://discord.gg/AJQGCCBcqf).
