### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by denselll** [heyvaldemar/outline-keycloak-traefik-letsencrypt-docker-compose#2]
Can't login to outline, getting "auth error" on the web page.

Docker logs : `"errors"self-signed certificate","level"s"error","message":"Error during authentication","stock"s"Errors self-signed certifica ten at TLSSocket.onConnectSecure (nodes tis rap:1550:34)\n at TLSSocket.emit (nodesevents:514:28)\n et TLSSocket.emit (node:domains489:12)\n at TLSSocket, finishinit (nodes 11s rap:967:8) at sal.onhandshakedone (nodes tis rap:743:12)"`

**Comment by heyvaldemar** [comment]
hey @denselll,

❗ It is important to note that you will need cryptographic certificates for your domain names. In my configuration, certificates are requested automatically using Traefik and Let’s Encrypt. **Remember that without a secure connection, the services will not work.**

❗ To obtain cryptographic certificates, you will need A-type records in the external DNS zone, which point to the IP address of your server where Traefik is installed. If you have created these records recently, you should wait before starting the installation of the services. Full replication of these records between DNS servers can take from a few minutes to 48 hours or even longer in rare cases.

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.
