### ISSUE TITLE
Unable to load image after being uploaded to Minio

### ISSUE THREAD

**Issue by jaimesdias** [heyvaldemar/outline-keycloak-traefik-letsencrypt-docker-compose#3]
Hi heyValdemar

First of all, nice work putting this howto together.

I did follow your howto, but whenever I upload an image it is uploaded to Minio, but then I get the following an error message on browser console like the following one: 
```
Uncaught Error: Error loading image: /api/attachments.redirect?id=829dfe43-101d-4e57-8b35-c49c03c518b7
    at a.onerror (insertFiles.ts:150:19)
```
It seems that the upload went well, but then Outline is unable to access the image on Minio. Thus, the image is still shown while on that page, but when I exit the page and come back again, the image is not shown. 

This is what is diferent from your howto:

1. The domain names are at all the same level:
`outline.domain.com, traefik-outline.domain.com, keycloak-outline.domain.com, minio-outline.domain.com, and console-minio-outline.domain.com`
2. Added a single commercial certificate with all the names (subjectaltnames):

- Created a folder `/home/outline/certs` with the certificates and the file `certificates.yaml` with the following content:

```
tls:
  certificates:
    # first certificate
    - certFile: /certs/outline.crt
      keyFile: /certs/outline.key
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /certs/outline.crt
        keyFile: /certs/outline.key
```

- Changed the `01-traefik-outline-letsencrypt-docker-compose.yml` file so that the services use the certificates:

``` services:
  traefik:
    image: ${TRAEFIK_IMAGE_TAG}
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--accesslog=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entryPoints.ping.address=:8082"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedByDefault=false"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - --providers.file.watch=true
      - --providers.file.directory=/certs/
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      - "--global.checkNewVersion=true"
      - "--global.sendAnonymousUsage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/outline/certs:/certs/
      - traefik-certificates:/etc/traefik/acme
```
The certificates are loaded correctly for all the domains.

**Comment by heyvaldemar** [comment]
hey @jaimesdias,

It appears that your problem pertains to the secure connection availability of MinIO.

I use [Traefik](https://traefik.io/traefik/) as a reverse proxy. It handles the obtaining of cryptographic certificates from [Let’s Encrypt](https://letsencrypt.org/) for your domain names and routes requests to the corresponding services based on those domains.

❗ Remember that without a secure connection, the services will not work.

❗ To obtain cryptographic certificates, you will need A-type records in the external DNS zone, which point to the IP address of your server where Traefik is installed. If you have created these records recently, you should wait before starting the installation of the services. Full replication of these records between DNS servers can take from a few minutes to 48 hours or even longer in rare cases.

For a more detailed discussion, please join me on my [Discord server](https://discord.gg/AJQGCCBcqf). It'll be more efficient.

**Comment by jaimesdias** [comment]
There was no issue with the connection (HTTPS), everything was working. I accessed Minio directly and the HTTPS connection works without any issue on the browser. 

Nonetheless, I added all the services names as alias to the outline.domain.com domain namem and reconfigured to use let's encrypt. The let's encrypt certificates were issues without problem. Minio and Outline are served over HTTPS without issues, but the problem remains. 

Do you have any more ideas?

**Comment by heyvaldemar** [comment]
For a more detailed discussion, please join me on my [Discord server](https://discord.gg/AJQGCCBcqf). It'll be more efficient.
