### ISSUE TITLE
ERROR: Invalid interpolation format for "command" option in service "backups-keycloak"

### ISSUE THREAD

**Issue by ercintorun** [heyvaldemar/outline-keycloak-traefik-letsencrypt-docker-compose#5]
Hello Valdemar, 

while trying to execute docker compose to keycloak file, I'm getting an error about the format for keycloak service command. Tried some variations, but couldn't manage. Is it related with the script, or I am doing something wrong .... 

root@outline-proxmox00:/home/outline/outline-keycloak-traefik-letsencrypt-docker-compose# docker-compose -f 02-keycloak-outline-docker-compose.yml -p keycloak up -d
ERROR: Invalid interpolation format for "command" option in service "backups-keycloak": "sh -c 'sleep $KEYCLOAK_BACKUP_INIT_SLEEP && while true; do
  pg_dump -h postgres-keycloak -p 5432 -d $KEYCLOAK_DB_NAME -U $KEYCLOAK_DB_USER | gzip > $KEYCLOAK_POSTGRES_BACKUPS_PATH/$KEYCLOAK_POSTGRES_BACKUP_NAME-$(date "+%Y-%m-%d_%H-%M").gz &&
  find $KEYCLOAK_POSTGRES_BACKUPS_PATH -type f -mtime +$KEYCLOAK_POSTGRES_BACKUP_PRUNE_DAYS | xargs rm -f &&
  sleep $KEYCLOAK_BACKUP_INTERVAL; done'"

**Comment by heyvaldemar** [comment]
hey @ercintorun,

I noticed you're currently using `docker-compose`. Just a heads-up, there's a newer tool available called `docker compose`.

For a seamless transition, feel free to check out my detailed [guide](https://www.heyvaldemar.com/install-outline-and-keycloak-using-docker-compose/).

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.

**Comment by ercintorun** [comment]
using "docker compose" instead of "docker-compose" solved the problem. May be a small warning might be good in the page. Thanks for the support.
