### ISSUE TITLE
KC_DB_URL_HOST should be postgres-keycloak

### ISSUE THREAD

**Issue by weironz** [heyvaldemar/outline-keycloak-traefik-letsencrypt-docker-compose#6]
KC_DB_URL_HOST should be `postgres-keycloak` in [02-keycloak-outline-docker-compose.yml](https://github.com/heyvaldemar/outline-keycloak-traefik-letsencrypt-docker-compose/blob/main/02-keycloak-outline-docker-compose.yml), not `postgres`.

**Comment by heyvaldemar** [comment]
hey @willzhang, thank you! Fixed.

If you’re interested in discussing more about DevOps or have more questions, feel free to join my DevOps community on Discord [here](https://discord.gg/AJQGCCBcqf). It’s a great place to share, learn, and collaborate with others in the field.
